import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d9e5e4",
        "error": "#ba1a1a",
        "tertiary-container": "#724b00",
        "tertiary-fixed-dim": "#fabb59",
        "on-secondary-fixed-variant": "#224b62",
        "on-tertiary-container": "#fbbc59",
        "surface-dim": "#d0dcdc",
        "on-surface-variant": "#3f484a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#3e657d",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004f55",
        "on-surface": "#131d1d",
        "on-primary-fixed": "#002023",
        "surface-tint": "#21676f",
        "secondary": "#3c637b",
        "on-tertiary-fixed": "#291800",
        "surface-container-highest": "#d9e5e4",
        "secondary-fixed": "#c6e7ff",
        "inverse-primary": "#90d1d9",
        "primary-fixed-dim": "#90d1d9",
        "inverse-on-surface": "#e7f3f3",
        "surface-container-low": "#eaf6f5",
        "inverse-surface": "#273232",
        "surface-bright": "#f0fcfb",
        "error-container": "#ffdad6",
        "primary": "#004349",
        "surface-container-high": "#deebea",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#a4cce7",
        "primary-container": "#0f5c63",
        "on-background": "#131d1d",
        "surface-container": "#e4f0f0",
        "on-error-container": "#93000a",
        "on-primary-container": "#91d2da",
        "tertiary-fixed": "#ffddb1",
        "outline-variant": "#bfc8c9",
        "tertiary": "#533600",
        "primary-fixed": "#aceef6",
        "on-primary": "#ffffff",
        "outline": "#6f797a",
        "background": "#f0fcfb",
        "surface": "#f0fcfb",
        "on-secondary-fixed": "#001e2d",
        "on-tertiary-fixed-variant": "#624000",
        "secondary-container": "#bae2fe",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        gutter: "16px",
        xl: "40px",
        md: "16px",
        lg: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        base: "4px",
      },
      fontFamily: {
        "mono-data": ["Inter", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["clamp(24px, 5vw, 32px)", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
